import { createFileRoute } from "@tanstack/react-router";
import { SITE_URL } from "@/lib/site";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Admin — BETASHINE" }], links: [{ rel: "canonical", href: `${SITE_URL}/admin` }] }), component: AdminPage });

type User = { id: string; email: string | null; full_name: string; username: string; phone: string; county: string; is_active: boolean; is_banned: boolean; balance: number; expenses: number; bonus: number; created_at: string };
type Payment = { id: string; user_id: string; paid_phone: string; status: string; created_at: string; profiles: { email: string | null; full_name: string; username: string; phone: string; is_active: boolean } | null };
type Withdrawal = { id: string; user_id: string; amount: number; phone: string; status: string; admin_note: string | null; created_at: string; profiles: { username: string; full_name: string; balance: number } | null };

type Tab = "users" | "deposits" | "withdrawals" | "notifications";

function AdminPage() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [admin,setAdmin]=useState(false); const [error,setError]=useState(""); const [tab,setTab]=useState<Tab>("users");
  const [users,setUsers]=useState<User[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [withdrawals,setWithdrawals]=useState<Withdrawal[]>([]); const [search,setSearch]=useState("");
  const [noteTitle,setNoteTitle]=useState(""); const [noteMessage,setNoteMessage]=useState(""); const [noteUser,setNoteUser]=useState("all");

  const load = async () => {
    const [u,p,w] = await Promise.all([
      supabase.from("profiles").select("id,email,full_name,username,phone,county,is_active,is_banned,balance,expenses,bonus,created_at").order("created_at",{ascending:false}),
      supabase.from("payment_submissions").select("id,user_id,paid_phone,status,created_at,profiles(email,full_name,username,phone,is_active)").order("created_at",{ascending:false}),
      supabase.from("withdrawal_requests").select("id,user_id,amount,phone,status,admin_note,created_at,profiles(username,full_name,balance)").order("created_at",{ascending:false}),
    ]);
    if (u.error) setError(u.error.message); else setUsers((u.data ?? []) as User[]);
    if (p.error) setError(p.error.message); else setPayments((p.data ?? []) as unknown as Payment[]);
    if (w.error) setError(w.error.message); else setWithdrawals((w.data ?? []) as unknown as Withdrawal[]);
  };
  useEffect(()=>{supabase.auth.getUser().then(async ({data})=>{if(data.user){const {data:ok}=await supabase.rpc("is_admin",{});if(ok){setAdmin(true);load();}}});},[]);
  async function login(e:React.FormEvent){e.preventDefault();setError("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError("Email au password si sahihi.");return;}const {data}=await supabase.rpc("is_admin",{});if(!data){await supabase.auth.signOut();setError("Akaunti hii si ya admin.");return;}setAdmin(true);load();}
  async function activate(p:Payment){const {error}=await supabase.rpc("admin_activate_user",{target_user_id:p.user_id,payment_id:p.id});if(error)setError(error.message);else load();}
  async function reject(p:Payment){const {error}=await supabase.rpc("admin_reject_payment",{target_user_id:p.user_id,payment_id:p.id});if(error)setError(error.message);else load();}
  async function status(u:User,active:boolean,banned:boolean){const {error}=await supabase.rpc("admin_set_user_status",{target_user_id:u.id,active,banned});if(error)setError(error.message);else load();}
  async function adjust(u:User){const raw=prompt(`Weka amount ya kuongeza/kupunguza balance ya ${u.username}. Tumia - kupunguza.`);if(raw===null)return;const delta=Number(raw);if(!Number.isFinite(delta))return setError("Amount si sahihi.");const {error}=await supabase.rpc("admin_adjust_balance",{target_user_id:u.id,amount_delta:delta});if(error)setError(error.message);else load();}
  async function resetPassword(u:User){const next=prompt(`Weka password mpya ya ${u.username} (angalau herufi 6):`);if(!next)return;const {data:s}=await supabase.auth.getSession();const r=await fetch("/api/admin-user",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${s.session?.access_token ?? ""}`},body:JSON.stringify({targetUserId:u.id,newPassword:next})});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||"Password haikuweza kubadilishwa");else alert("Password imebadilishwa.");}
  async function reviewWithdrawal(id:string,nextStatus:string){const note=prompt("Admin note (optional):") ?? "";const {error}=await supabase.rpc("admin_review_withdrawal",{request_id:id,next_status:nextStatus,note});if(error)setError(error.message);else load();}
  async function sendNotification(){if(!noteTitle.trim()||!noteMessage.trim())return setError("Jaza title na message.");let ids=users.map(u=>u.id);if(noteUser!=="all")ids=[noteUser];const rows=ids.map(user_id=>({user_id,title:noteTitle.trim(),message:noteMessage.trim()}));const {error}=await supabase.from("notifications").insert(rows);if(error)setError(error.message);else{setNoteTitle("");setNoteMessage("");setNoteUser("all");alert(`Notification imetumwa kwa ${rows.length} user.`);}}
  const filtered=useMemo(()=>users.filter(u=>`${u.username} ${u.full_name} ${u.email??""} ${u.phone}`.toLowerCase().includes(search.toLowerCase())),[users,search]);

  if(!admin)return <div className="mx-auto max-w-sm px-4 py-12"><div className="rounded-2xl bg-card p-6 shadow-card"><h1 className="text-2xl font-extrabold text-center">🔐 Admin Login</h1><form onSubmit={login} className="mt-5 space-y-3"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Admin email" className="w-full rounded-xl border p-3"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" className="w-full rounded-xl border p-3"/><button className="w-full rounded-xl bg-primary p-3 font-extrabold text-primary-foreground">Ingia</button></form>{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}</div></div>;

  return <div className="min-h-screen bg-background px-3 py-6"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Admin Dashboard</h1><p className="text-sm text-muted-foreground">Manage users, deposits, withdrawals na notifications.</p></div><button onClick={()=>supabase.auth.signOut().then(()=>setAdmin(false))} className="rounded-xl border px-4 py-2 font-bold">Logout</button></div>
    <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{(["users","deposits","withdrawals","notifications"] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-3 py-3 text-sm font-extrabold ${tab===t?"bg-primary text-primary-foreground":"bg-card"}`}>{t === "users" ? "👥 Users" : t === "deposits" ? "💳 Deposits" : t === "withdrawals" ? "💰 Withdrawals" : "🔔 Notifications"}</button>)}</div>

    {tab==="users"&&<section className="mt-5"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search username, name, email or phone..." className="w-full rounded-xl border bg-card px-4 py-3"/><div className="mt-4 grid gap-3">{filtered.map(u=><div key={u.id} className="rounded-2xl bg-card p-4 shadow-card"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-black">{u.username} <span className="text-sm font-semibold text-muted-foreground">({u.full_name})</span></h2><p className="text-sm">{u.email??"—"} · {u.phone}</p><p className="text-sm text-muted-foreground">Balance: <strong className="text-foreground">TZS {Number(u.balance).toLocaleString()}</strong> · Expenses: {Number(u.expenses).toLocaleString()} · Bonus: {Number(u.bonus).toLocaleString()}</p></div><div className="text-right text-sm"><p className={u.is_banned?"font-black text-destructive":"font-bold text-success"}>{u.is_banned?"BANNED":u.is_active?"ACTIVE":"INACTIVE"}</p></div></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>status(u,!u.is_active,u.is_banned)} className="rounded-lg border px-3 py-2 text-sm font-bold">{u.is_active?"Deactivate":"Activate"}</button><button onClick={()=>status(u,u.is_active,!u.is_banned)} className="rounded-lg border border-destructive px-3 py-2 text-sm font-bold text-destructive">{u.is_banned?"Unban":"Ban"}</button><button onClick={()=>adjust(u)} className="rounded-lg border px-3 py-2 text-sm font-bold">Adjust Balance</button><button onClick={()=>resetPassword(u)} className="rounded-lg border px-3 py-2 text-sm font-bold">Reset Password</button></div></div>)}</div></section>}

    {tab==="deposits"&&<section className="mt-5 space-y-3">{payments.map(p=><div key={p.id} className="rounded-2xl bg-card p-4 shadow-card"><div className="grid gap-2 sm:grid-cols-2"><div><p className="font-black">{p.profiles?.username??"User"} — {p.profiles?.full_name??""}</p><p className="text-sm">Email: {p.profiles?.email??"—"}</p><p className="text-sm">Simu ya malipo: <strong>{p.paid_phone}</strong></p></div><div><p className="text-sm">Status: <strong>{p.status}</strong></p><p className="text-xs text-muted-foreground">{new Date(p.created_at).toLocaleString()}</p></div></div>{p.status==="pending"&&<div className="mt-3 flex gap-2"><button onClick={()=>activate(p)} className="rounded-xl bg-primary px-4 py-2 font-extrabold text-primary-foreground">✅ Approve Deposit</button><button onClick={()=>reject(p)} className="rounded-xl border border-destructive px-4 py-2 font-extrabold text-destructive">Reject</button></div>}</div>)}{payments.length===0&&<div className="rounded-2xl bg-card p-8 text-center">Hakuna deposit submissions.</div>}</section>}

    {tab==="withdrawals"&&<section className="mt-5 space-y-3">{withdrawals.map(w=><div key={w.id} className="rounded-2xl bg-card p-4 shadow-card"><div className="grid gap-2 sm:grid-cols-2"><div><p className="font-black">{w.profiles?.username??"User"} — {w.profiles?.full_name??""}</p><p className="text-sm">Amount: <strong>TZS {Number(w.amount).toLocaleString()}</strong></p><p className="text-sm">Phone: {w.phone}</p><p className="text-sm">Current balance: TZS {Number(w.profiles?.balance??0).toLocaleString()}</p></div><div><p className="text-sm">Status: <strong>{w.status}</strong></p><p className="text-xs text-muted-foreground">{new Date(w.created_at).toLocaleString()}</p></div></div>{w.status==="pending"&&<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>reviewWithdrawal(w.id,"approved")} className="rounded-xl bg-primary px-4 py-2 font-extrabold text-primary-foreground">✅ Approve</button><button onClick={()=>reviewWithdrawal(w.id,"rejected")} className="rounded-xl border border-destructive px-4 py-2 font-extrabold text-destructive">Reject</button></div>}</div>)}{withdrawals.length===0&&<div className="rounded-2xl bg-card p-8 text-center">Hakuna withdrawal requests.</div>}</section>}

    {tab==="notifications"&&<section className="mt-5 rounded-2xl bg-card p-5 shadow-card"><h2 className="text-xl font-black">Tuma Notification</h2><div className="mt-4 grid gap-3"><select value={noteUser} onChange={e=>setNoteUser(e.target.value)} className="rounded-xl border bg-background px-3 py-3"><option value="all">📢 Watumiaji wote</option>{users.map(u=><option key={u.id} value={u.id}>@{u.username} — {u.full_name}</option>)}</select><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="Title / kichwa" className="rounded-xl border bg-background px-3 py-3"/><textarea value={noteMessage} onChange={e=>setNoteMessage(e.target.value)} placeholder="Andika ujumbe wa notification..." rows={6} className="rounded-xl border bg-background px-3 py-3"/><button onClick={sendNotification} className="rounded-xl bg-primary px-4 py-3 font-extrabold text-primary-foreground">📣 Tuma Notification</button></div></section>}
    {error&&<p className="mt-4 rounded-xl bg-destructive/10 p-3 text-sm font-semibold text-destructive">{error}</p>}
  </div></div>;
}
