import { createFileRoute } from "@tanstack/react-router";
import { SITE_URL } from "@/lib/site";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/admin")({ head: () => ({ meta: [{ title: "Admin — BETASHINE" }], links: [{ rel: "canonical", href: `${SITE_URL}/admin` }] }), component: AdminPage });

type Payment = { id: string; user_id: string; paid_phone: string; status: string; created_at: string; profiles: { email: string | null; full_name: string; username: string; phone: string; is_active: boolean } | null };

function AdminPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [admin, setAdmin] = useState(false); const [items, setItems] = useState<Payment[]>([]); const [error, setError] = useState("");
  const load = async () => { const { data, error } = await supabase.from("payment_submissions").select("id,user_id,paid_phone,status,created_at,profiles(email,full_name,username,phone,is_active)").order("created_at", { ascending: false }); if (error) setError(error.message); else setItems((data ?? []) as unknown as Payment[]); };
  useEffect(() => { supabase.auth.getUser().then(async ({ data }) => { if (data.user) { const { data: ok } = await supabase.rpc("is_admin", {}); if (ok) { setAdmin(true); load(); } } }); }, []);
  async function login(e: React.FormEvent) { e.preventDefault(); setError(""); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { setError("Email au password si sahihi."); return; } const { data } = await supabase.rpc("is_admin", {}); if (!data) { await supabase.auth.signOut(); setError("Akaunti hii si ya admin."); return; } setAdmin(true); load(); }
  async function activate(item: Payment) { const { error } = await supabase.rpc("admin_activate_user", { target_user_id: item.user_id, payment_id: item.id }); if (error) setError(error.message); else load(); }
  async function reject(item: Payment) { const { error } = await supabase.rpc("admin_reject_payment", { target_user_id: item.user_id, payment_id: item.id }); if (error) setError(error.message); else load(); }
  if (!admin) return <div className="mx-auto max-w-sm px-4 py-12"><div className="rounded-2xl bg-card p-6 shadow-card"><h1 className="text-2xl font-extrabold text-center">🔐 Admin Login</h1><form onSubmit={login} className="mt-5 space-y-3"><input value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="Admin email" className="w-full rounded-xl border p-3"/><input value={password} onChange={(e) => setPassword(e.target.value)} type="password" placeholder="Password" className="w-full rounded-xl border p-3"/><button className="w-full rounded-xl bg-primary p-3 font-extrabold text-primary-foreground">Ingia</button></form>{error && <p className="mt-3 text-sm text-destructive">{error}</p>}</div></div>;
  return <div className="min-h-screen bg-background px-3 py-6"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><h1 className="text-2xl font-extrabold">Admin Dashboard</h1><button onClick={() => supabase.auth.signOut().then(() => setAdmin(false))} className="rounded-xl border px-3 py-2 font-bold">Logout</button></div><p className="mt-1 text-sm text-muted-foreground">Maombi ya malipo na taarifa za users.</p><div className="mt-5 space-y-3">{items.map((item) => <div key={item.id} className="rounded-2xl bg-card p-4 shadow-card"><div className="grid gap-2 sm:grid-cols-2"><div><p className="font-extrabold">{item.profiles?.full_name ?? "User"}</p><p className="text-sm">Email: {item.profiles?.email ?? "—"}</p><p className="text-sm">Username: {item.profiles?.username}</p><p className="text-sm">Namba ya usajili: {item.profiles?.phone}</p></div><div><p className="text-sm">Namba iliyolipia: <strong>{item.paid_phone}</strong></p><p className="text-sm">Status: <strong>{item.status}</strong></p><p className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</p></div></div>{item.status === "pending" && <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => activate(item)} className="rounded-xl bg-primary px-4 py-2.5 font-extrabold text-primary-foreground">✅ Activate Account</button><button onClick={() => reject(item)} className="rounded-xl border border-destructive px-4 py-2.5 font-extrabold text-destructive">❌ Reject Payment</button></div>}</div>)}{items.length === 0 && <div className="rounded-2xl bg-card p-8 text-center">Hakuna maombi ya malipo bado.</div>}</div>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}</div></div>;
}
